# Generated by Django 5.2.13 on 2026-04-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='ModeloEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Modelo')),
                ('version', models.IntegerField(verbose_name='Versión del Modelo')),
                ('activo', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Modelo Evaluación',
                'verbose_name_plural': 'Modelos Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.dependencia', verbose_name='Dependencia')),
                ('modelo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.modeloevaluacion', verbose_name='Modelo Evaluación')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.periodo', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Pilar')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('modelo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.modeloevaluacion')),
            ],
            options={
                'verbose_name': 'Pilar',
                'verbose_name_plural': 'Pilares',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Indicador')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.pilar')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Subindicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Subindicador')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.indicador')),
            ],
            options={
                'verbose_name': 'Subindicador',
                'verbose_name_plural': 'Subindicadores',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje')),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderación')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.evaluacion', verbose_name='Evaluación')),
                ('subindicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.subindicador', verbose_name='Subindicador')),
            ],
            options={
                'verbose_name': 'Evaluación Resultado',
                'verbose_name_plural': 'Evaluaciones Resultado',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Criterio')),
                ('rango', models.CharField(max_length=255, verbose_name='Peso')),
                ('subindicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.subindicador')),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
            },
        ),
        migrations.CreateModel(
            name='DependenciaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.dependencia', verbose_name='Dependencia')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.modeloevaluacion')),
            ],
            options={
                'verbose_name': 'Dependencia Modelo',
                'verbose_name_plural': 'Dependencias Modelo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('dependencia',), name='unique_modelo_activo_por_dependencia'), models.UniqueConstraint(fields=('dependencia', 'modelo'), name='unique_dependencia_modelo')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(fields=('periodo', 'dependencia'), name='unique_periodo_dependencia'),
        ),
        migrations.AddIndex(
            model_name='evaluacionresultado',
            index=models.Index(fields=['evaluacion'], name='evaluacion'),
        ),
        migrations.AddIndex(
            model_name='evaluacionresultado',
            index=models.Index(fields=['subindicador'], name='subindicador'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionresultado',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'subindicador'), name='unique_evaluacion_subindicador'),
        ),
    ]
