# Generated by Django 5.2.13 on 2026-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Criterio'),
        ),
        migrations.AlterField(
            model_name='evaluacionresultado',
            name='ponderacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Ponderación'),
        ),
        migrations.AlterField(
            model_name='evaluacionresultado',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='pilar',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Pilar'),
        ),
        migrations.AlterField(
            model_name='subindicador',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Subindicador'),
        ),
    ]
