# Generated by Django 5.2.13 on 2026-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_criterio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionresultado',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
