# Generated by Django 5.2.13 on 2026-04-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_evaluacionresultado_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='pilar',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='subindicador',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
    ]
