# Generated by Django 5.2.13 on 2026-04-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_categoria_orden_criterio_orden_indicador_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subindicador',
            name='tipo_calculo',
            field=models.CharField(choices=[('mensual', 'Mesual'), ('directo', 'Directo')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EvaluacionResultadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.evaluacionresultado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resultado', 'mes'), name='unique_resultado_mes')],
            },
        ),
    ]
