# Generated by Django 5.2.13 on 2026-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
