# Generated by Django 5.2.13 on 2026-06-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_evaluacion_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
