# Generated by Django 5.2.13 on 2026-06-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_periodo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='activa',
        ),
    ]
