# Generated by Django 5.2.13 on 2026-06-20 21:33
# Editada manualmente: conversion segura de `nombre` (CharField) a ForeignKey
# hacia los catalogos, preservando los datos existentes.

import django.db.models.deletion
from django.db import migrations, models


def poblar_categorias(apps, schema_editor):
    """Crea una categoria por cada nombre de texto existente y enlaza el FK."""
    for modelo_nombre, cat_nombre in (
        ("Pilar", "PilarCategoria"),
        ("Indicador", "IndicadorCategoria"),
        ("Subindicador", "SubindicadorCategoria"),
    ):
        Modelo = apps.get_model("contenido", modelo_nombre)
        Cat = apps.get_model("contenido", cat_nombre)
        cache = {}
        for obj in Modelo.objects.all():
            texto = (obj.nombre_txt or "").strip() or "(sin nombre)"
            cat = cache.get(texto)
            if cat is None:
                cat, _ = Cat.objects.get_or_create(nombre=texto)
                cache[texto] = cat
            obj.nombre = cat
            obj.save(update_fields=["nombre"])


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0010_remove_evaluacion_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Indicador',
                'verbose_name_plural': 'Categorías de Indicadores',
            },
        ),
        migrations.CreateModel(
            name='PilarCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Pilar',
                'verbose_name_plural': 'Categorías de Pilares',
            },
        ),
        migrations.CreateModel(
            name='SubindicadorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Subindicador',
                'verbose_name_plural': 'Categorías de Subindicador',
            },
        ),

        # 1) Renombrar la columna de texto para conservar su contenido.
        migrations.RenameField(model_name='pilar', old_name='nombre', new_name='nombre_txt'),
        migrations.RenameField(model_name='indicador', old_name='nombre', new_name='nombre_txt'),
        migrations.RenameField(model_name='subindicador', old_name='nombre', new_name='nombre_txt'),

        # 2) Agregar el nuevo FK (nullable temporalmente, sin default).
        migrations.AddField(
            model_name='pilar',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.pilarcategoria'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.indicadorcategoria'),
        ),
        migrations.AddField(
            model_name='subindicador',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.subindicadorcategoria'),
        ),

        # 3) Poblar los catalogos desde el texto y enlazar.
        migrations.RunPython(poblar_categorias, migrations.RunPython.noop),

        # 4) Volver el FK obligatorio (igual que en el modelo).
        migrations.AlterField(
            model_name='pilar',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.pilarcategoria'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.indicadorcategoria'),
        ),
        migrations.AlterField(
            model_name='subindicador',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.subindicadorcategoria'),
        ),

        # 5) Eliminar la columna de texto temporal.
        migrations.RemoveField(model_name='pilar', name='nombre_txt'),
        migrations.RemoveField(model_name='indicador', name='nombre_txt'),
        migrations.RemoveField(model_name='subindicador', name='nombre_txt'),
    ]
