# Generated by Django 5.2.13 on 2026-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_indicadorcategoria_pilarcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadorcategoria',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='subindicadorcategoria',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Categoría'),
        ),
    ]
