# Generated by Django 5.2.13 on 2026-06-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_alter_indicadorcategoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='nombre',
            field=models.TextField(verbose_name='Criterio'),
        ),
    ]
