# Generated by Django 5.2.13 on 2026-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_alter_criterio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='publico',
            field=models.BooleanField(default=True),
        ),
    ]
