# Generated by Django 5.2.13 on 2026-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_periodo_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
