# Generated by Django 5.2.13 on 2026-06-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_grupo_evaluador'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.categoria'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='umbral',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
