# Generated by Django 5.2.13 on 2026-06-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_dependencia_categoria_periodo_umbral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='categoria',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.categoria'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='vigencia',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
