# Generated by Django 5.2.13 on 2026-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_remove_dependencia_categoria_evaluacion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionresultado',
            name='ponderacion',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Ponderación'),
        ),
        migrations.AlterField(
            model_name='evaluacionresultado',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='evaluacionresultadodetalle',
            name='ponderacion',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='evaluacionresultadodetalle',
            name='puntaje',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='peso',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='pilar',
            name='peso',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='subindicador',
            name='peso',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Peso'),
        ),
    ]
