# Generated by Django 5.2.13 on 2026-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0019_alter_evaluacionresultado_ponderacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subindicador',
            name='tipo_calculo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('directo', 'Directo')], max_length=20, null=True),
        ),
    ]
